namespace Galaxy.HabboHotel.Items.Wired
{
    public enum WiredBoxType
    {
        None,
        TriggerRoomEnter,
        TriggerUserSays,
        TriggerRepeat,
        TriggerLongRepeat,
        TriggerLongTrigger,
        TriggerStateChanges,
        TriggerWalkOnFurni,
        TriggerWalkOffFurni,
        TriggerGameStarts,
        TriggerGameEnds,
        TriggerUserFurniCollision,
        TriggerUserSaysCommand,
        TriggerBotReachFurni,
        TriggerBotReachUser,
        TriggerAtGivenTime, 
        TriggerBotReachUserBox,
        TriggerUserAFKBox,
        TriggerSpaceFazGol,
        TriggerUserSaiDoQuarto,
        EffectBotMudaMissao,

        EffectShowMessage,
        EffectTeleportToFurni,
        EffectToggleFurniState,
        EffectKickUser,
        EffectMatchPosition,
        EffectMoveAndRotate,
        EffectMoveFurniToNearestUser,
        EffectMoveFurniFromNearestUser,
        EffectMoveFurniToUserBox,
        EffectMoveFurniFromUserBox,
        EffectMuteTriggerer,
        EffectGiveReward,
        EffectEnableTeleportUserBox,
        EffectExecuteWiredStacks,
        EffectCloseDice,
        EffectAddScore,
        EffectGiveFurni,
        ShowAlertPHBox,
        EffectTeleportBotToFurniBox,
        EffectBotChangesClothesBox,
        EffectBotMovesToFurniBox,
        EffectBotCommunicatesToAllBox,
        EffectBotCommunicatesToUserBox,
        EffectBotFollowsUserBox,
        EffectBotGivesHanditemBox,
        EffectAddActorToTeam,
        EffectRemoveActorFromTeam,
        EffectSetRollerSpeed,
        EffectRegenerateMaps,
        EffectGiveUserBadge,
        EffectEnableUserBox,
        EffectDanceUserBox,
        EffectGiveUserCreditsBox,
        EffectGiveUserDucketsBox,
        EffectGiveUserDiamondsBox,
        EffectHandUserItemBox,
        EffectFreezeUserBox,
        EffectFixRoomBox,
        EffectFastWalkUserBox,
        EffectMoveUserToFurniBox,
        EffectSendToRoomUserBox,
        EffectApplyClothes,
        EffectProgressUserAchievement,
        EffectToggleNegativeFurniState,
        EffectTimerReset,
        EffectMoveUser,
        EffectAddRewardPoints,
        EffectMoveToDir,
        EffectGiveFurniUmaVezBox,
        SendGrapicAlertPHB,
        EffectMoveUserBox,
        EffectBotCopiaVisual,
		SendVideoToUserBox,

		ConditionFurniHasUsers,
        ConditionFurniHasFurni,
        ConditionTriggererOnFurni,
        ConditionIsGroupMember,
        ConditionIsNotGroupMember,
        ConditionTriggererNotOnFurni,
        ConditionFurniHasNoUsers,
        ConditionIsWearingBadge,
        ConditionIsWearingFX,
        ConditionIsNotWearingBadge,
        ConditionIsNotWearingFX,
        ConditionMatchStateAndPosition,
        ConditionDontMatchStateAndPosition,
        ConditionUserCountInRoom,
        ConditionUserCountDoesntInRoom,
        ConditionFurniTypeMatches,
        ConditionFurniTypeDoesntMatch,
        ConditionFurniHasNoFurni,
        ConditionActorHasHandItemBox,
        ConditionActorHasNotHandItemBox,
        ConditionActorIsInTeamBox,
        ConditionActorIsNotInTeamBox,
        ConditionWearingClothes,
        ConditionNotWearingClothes,
        ConditionDateRangeActive,
        ConditionLessSecs,
        ConditionMoreSecs,
        SendCustomMessageBox,
        TotalUsersCoincidence,
        ConditionLessThanTimer,
        ConditionMoreThanTimer,
        ConditionSpaceHasDiamonds, /// PHB (condição: usuário tem isso ou mais diamantes )
        ConditionSpaceHasCredits, /// PHB (condição: usuário tem isso ou mais créditos )
        ConditionSpaceHasMeteoritos, /// PHB (condição: usuário tem isso ou mais meteoritos/gotw )
        ConditionSpaceHasDuckets, // PHB (condição: usuario tem isso ou mais duckets/activity_points/pixels)
        ConditionSpaceNoHasDiamonds, /// PHB (condição: usuário tem isso ou mais diamantes ) negativa
        ConditionSpaceNoHasCredits, /// PHB (condição: usuário tem isso ou mais créditos ) negativa
        ConditionSpaceNoHasMeteoritos, /// PHB (condição: usuário tem isso ou mais meteoritos/gotw ) negativa
        ConditionSpaceNoHasDuckets, // PHB (condição: usuario tem isso ou mais duckets/activity_points/pixels) negativa
        ConditionSpaceHasRank, // PHB rank positivo
        ConditionSpaceNoHasRank, // PHB rank negativo
        ConditionSpaceUserIdle, // PHB usuario ausente positivo
        ConditionDonoEstaNoQuarto,
        ConditionDonoNaoEstaNoQuarto,

        AddonRandomEffect,
        HighscoreClassicAlltime,
		TeleportFurniBox
	}
}